name: Publish to Modrinth

on:
  push:
    branches: [ main ]
    paths:
    - 'src/main/**/*'
    - 'changes.md'
    
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: publish
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      run: |
        chmod a+x ./gradlew
        ./gradlew modrinth