name: Publish to CurseForge

on:
  push:
    branches: [ main ]
    paths:
    - 'src/main/**/*'
    - 'changes.md'
    
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: publish
      env:
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      run: |
        chmod a+x ./gradlew
        ./gradlew curseforge